; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 -verify-machineinstrs < %s | FileCheck %s

; SILowerControlFlow::removeMBBifRedundant deletes a redundant control-flow
; block. When LiveIntervals is available (as it is once it runs before
; PHIElimination) the block's slot range must be removed from SlotIndexes and
; the live ranges spanning it recomputed; otherwise the machine verifier trips
; on stale slot-index and live-range state. Exercised by a divergent self-loop,
; which produces the redundant Flow blocks that get removed.

define void @f(ptr addrspace(1) %arg, i32 %cnd0) {
; CHECK-LABEL: f:
; CHECK:       ; %bb.0: ; %bb0
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v2
; CHECK-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; CHECK-NEXT:    s_cbranch_execz .LBB0_3
; CHECK-NEXT:  ; %bb.1: ; %bb2.preheader
; CHECK-NEXT:    s_mov_b64 s[6:7], 0
; CHECK-NEXT:  .LBB0_2: ; %bb2
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    v_mov_b32 v3, 0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v3
; CHECK-NEXT:    s_or_b64 s[6:7], vcc, s[6:7]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[6:7]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_2
; CHECK-NEXT:  .LBB0_3: ; %Flow1
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    global_store_dword v[0:1], v2, off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
bb0:
  %cmp0 = icmp eq i32 %cnd0, 0
  br i1 %cmp0, label %bb2, label %bb3

bb2:
  %val = call i32 asm sideeffect "v_mov_b32 $0, 0", "=v"()
  %cmp1 = icmp eq i32 %val, 0
  br i1 %cmp1, label %bb2, label %bb3

bb3:
  store volatile i32 %cnd0, ptr addrspace(1) %arg
  ret void
}
