; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=xtensa -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The select pseudo is expanded by a custom inserter into a diamond with a value
; merge in the join block. Under -sdag-use-block-args that merge must be a block
; argument fed by SUCC_ARGS, not a machine PHI.
define i32 @select_custom_inserter(i32 %c, i32 %a, i32 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    movi a8, 0
; CHECK-NEXT:    bne a2, a8, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    or a3, a4, a4
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    or a2, a3, a3
; CHECK-NEXT:    ret
  %cmp = icmp ne i32 %c, 0
  %r = select i1 %cmp, i32 %a, i32 %b
  ret i32 %r
}
