; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=xtensa -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through this target's control-flow lowering.

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    addi a8, a1, -32
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    s32i a0, a1, 20 # 4-byte Folded Spill
; CHECK-NEXT:    s32i a12, a1, 16 # 4-byte Folded Spill
; CHECK-NEXT:    s32i a13, a1, 12 # 4-byte Folded Spill
; CHECK-NEXT:    s32i a14, a1, 8 # 4-byte Folded Spill
; CHECK-NEXT:    s32i a15, a1, 4 # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset a0, -4
; CHECK-NEXT:    .cfi_offset a12, -8
; CHECK-NEXT:    .cfi_offset a13, -12
; CHECK-NEXT:    .cfi_offset a14, -16
; CHECK-NEXT:    .cfi_offset a15, -20
; CHECK-NEXT:    or a12, a3, a3
; CHECK-NEXT:    or a13, a2, a2
; CHECK-NEXT:    movi a2, 0
; CHECK-NEXT:    movi a8, 3
; CHECK-NEXT:    s32i a8, a1, 0 # 4-byte Folded Spill
; CHECK-NEXT:    l32r a14, .LCPI0_0
; CHECK-NEXT:    or a15, a2, a2
; CHECK-NEXT:    j .LBB0_2
; CHECK-NEXT:  .LBB0_1: # %latch
; CHECK-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    or a8, a2, a2
; CHECK-NEXT:    add a2, a8, a15
; CHECK-NEXT:    addi a15, a15, 1
; CHECK-NEXT:    bge a15, a13, .LBB0_4
; CHECK-NEXT:  .LBB0_2: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    bne a12, a15, .LBB0_1
; CHECK-NEXT:  # %bb.3: # %then
; CHECK-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    l32i a3, a1, 0 # 4-byte Folded Reload
; CHECK-NEXT:    callx0 a14
; CHECK-NEXT:    j .LBB0_1
; CHECK-NEXT:  .LBB0_4: # %exit
; CHECK-NEXT:    add a8, a8, a15
; CHECK-NEXT:    addi a2, a8, -1
; CHECK-NEXT:    l32i a15, a1, 4 # 4-byte Folded Reload
; CHECK-NEXT:    l32i a14, a1, 8 # 4-byte Folded Reload
; CHECK-NEXT:    l32i a13, a1, 12 # 4-byte Folded Reload
; CHECK-NEXT:    l32i a12, a1, 16 # 4-byte Folded Reload
; CHECK-NEXT:    l32i a0, a1, 20 # 4-byte Folded Reload
; CHECK-NEXT:    addi a8, a1, 32
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    ret
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
