; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sparc -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through SPARC's control-flow lowering.

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0: ! %entry
; CHECK-NEXT:    mov %g0, %o2
; CHECK-NEXT:    ba .LBB0_3
; CHECK-NEXT:    mov %g0, %o3
; CHECK-NEXT:  .LBB0_1: ! %then
; CHECK-NEXT:    ! in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    smul %o3, 3, %o4
; CHECK-NEXT:  .LBB0_2: ! %latch
; CHECK-NEXT:    ! in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    add %o4, %o2, %o3
; CHECK-NEXT:    add %o2, 1, %o2
; CHECK-NEXT:    cmp %o2, %o0
; CHECK-NEXT:    bge .LBB0_5
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_3: ! %loop
; CHECK-NEXT:    ! =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmp %o1, %o2
; CHECK-NEXT:    be .LBB0_1
; CHECK-NEXT:    nop
; CHECK-NEXT:  ! %bb.4: ! in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    ba .LBB0_2
; CHECK-NEXT:    mov %o3, %o4
; CHECK-NEXT:  .LBB0_5: ! %exit
; CHECK-NEXT:    add %o4, %o2, %o0
; CHECK-NEXT:    retl
; CHECK-NEXT:    add %o0, -1, %o0
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
