; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sparc -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The select pseudo is expanded by a custom inserter into a diamond with a value
; merge in the join block. Under -sdag-use-block-args that merge must be a block
; argument fed by SUCC_ARGS, not a machine PHI.
define i32 @select_custom_inserter(i32 %c, i32 %a, i32 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp %o0, 0
; CHECK-NEXT:    bne .LBB0_2
; CHECK-NEXT:    mov %o1, %o0
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    mov %o2, %o0
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    retl
; CHECK-NEXT:    nop
  %cmp = icmp ne i32 %c, 0
  %r = select i1 %cmp, i32 %a, i32 %b
  ret i32 %r
}
