; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=bpfel -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The Select pseudo is expanded by a custom inserter into a diamond with a value
; merge in the join block. Under -sdag-use-block-args that merge must be a block
; argument fed by SUCC_ARGS, not a machine PHI.
define i64 @select_custom_inserter(i64 %c, i64 %a, i64 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:       # %bb.0:
; CHECK-NEXT:    r0 = r2
; CHECK-NEXT:    if r1 != 0 goto .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    r0 = r3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    exit
  %cmp = icmp ne i64 %c, 0
  %r = select i1 %cmp, i64 %a, i64 %b
  ret i64 %r
}
