; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=bpfel -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through BPF's control-flow lowering, and via the
; loop-carried zext through the BPFMIPeephole ZExt-elimination pass, which runs
; before PHI elimination and walks def chains that now cross block arguments.

define i64 @zext_loop(ptr %p, i32 %n) {
; CHECK-LABEL: zext_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r0 = 0
; CHECK-NEXT:    w3 = 0
; CHECK-NEXT:    w1 = *(u32 *)(r1 + 0)
; CHECK-NEXT:  .LBB0_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    r0 += r1
; CHECK-NEXT:    w3 += 1
; CHECK-NEXT:    if w3 s< w2 goto .LBB0_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    exit
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %loop ]
  %v = load i32, ptr %p
  %z = zext i32 %v to i64
  %acc.next = add i64 %acc, %z
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i64 %acc.next
}

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w4 = 0
; CHECK-NEXT:    w3 = 0
; CHECK-NEXT:    goto .LBB1_1
; CHECK-NEXT:  .LBB1_3: # %latch
; CHECK-NEXT:    # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    w0 = w4
; CHECK-NEXT:    w4 += w3
; CHECK-NEXT:    w3 += 1
; CHECK-NEXT:    if w3 s< w1 goto .LBB1_1
; CHECK-NEXT:  # %bb.4: # %exit
; CHECK-NEXT:    w0 += w3
; CHECK-NEXT:    w0 += -1
; CHECK-NEXT:    exit
; CHECK-NEXT:  .LBB1_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    if w2 != w3 goto .LBB1_3
; CHECK-NEXT:  # %bb.2: # %then
; CHECK-NEXT:    # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    w4 *= 3
; CHECK-NEXT:    goto .LBB1_3
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
