; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=s390x-linux-gnu -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; SystemZ custom inserters build value merges for selects, atomic loops, the
; memory and string loops, probed alloca, and setjmp. Under -sdag-use-block-args
; those merges must be block arguments fed by SUCC_ARGS, not machine PHIs. The
; loop inserters build their loop-header merges after the loop body so the
; self-edge SUCC_ARGS forwarders land in the terminator-adjacent cluster.

@g = global i32 0

define i32 @select_custom_inserter(i32 %a, i32 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:       # %bb.0:
; CHECK-NEXT:    larl %r1, g@GOT
; CHECK-NEXT:    chsi 4(%r1), 0
; CHECK-NEXT:    blhr %r14
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    lr %r2, %r3
; CHECK-NEXT:    br %r14
  %c = icmp ne i32 ptrtoint (ptr @g to i32), 0
  %r = select i1 %c, i32 %a, i32 %b
  ret i32 %r
}

define i8 @atomicrmw_min_loop(ptr %p, i8 %v) {
; CHECK-LABEL: atomicrmw_min_loop:
; CHECK:       # %bb.0:
; CHECK-NEXT:    risbg %r1, %r2, 0, 189, 0
; CHECK-NEXT:    l %r0, 0(%r1)
; CHECK-NEXT:    sll %r3, 24
; CHECK-NEXT:    sll %r2, 3
; CHECK-NEXT:    lcr %r4, %r2
; CHECK-NEXT:  .LBB1_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    rll %r5, %r0, 0(%r2)
; CHECK-NEXT:    crjle %r5, %r3, .LBB1_3
; CHECK-NEXT:  # %bb.2: # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    risbg %r5, %r3, 32, 39, 0
; CHECK-NEXT:  .LBB1_3: # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    rll %r5, %r5, 0(%r4)
; CHECK-NEXT:    cs %r0, %r5, 0(%r1)
; CHECK-NEXT:    jl .LBB1_1
; CHECK-NEXT:  # %bb.4:
; CHECK-NEXT:    rll %r2, %r0, 8(%r2)
; CHECK-NEXT:    br %r14
  %r = atomicrmw min ptr %p, i8 %v seq_cst
  ret i8 %r
}

define i8 @cmpxchg_subword_loop(ptr %p, i8 %c, i8 %n) {
; CHECK-LABEL: cmpxchg_subword_loop:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r13, %r15, 104(%r15)
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    risbg %r1, %r2, 0, 189, 0
; CHECK-NEXT:    l %r5, 0(%r1)
; CHECK-NEXT:    llcr %r3, %r3
; CHECK-NEXT:    sll %r2, 3
; CHECK-NEXT:    lcr %r14, %r2
; CHECK-NEXT:  .LBB2_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    rll %r0, %r5, 8(%r2)
; CHECK-NEXT:    risbg %r4, %r0, 32, 55, 0
; CHECK-NEXT:    llcr %r0, %r0
; CHECK-NEXT:    crjlh %r0, %r3, .LBB2_3
; CHECK-NEXT:  # %bb.2: # in Loop: Header=BB2_1 Depth=1
; CHECK-NEXT:    rll %r13, %r4, -8(%r14)
; CHECK-NEXT:    cs %r5, %r13, 0(%r1)
; CHECK-NEXT:    jl .LBB2_1
; CHECK-NEXT:  .LBB2_3:
; CHECK-NEXT:    lr %r2, %r0
; CHECK-NEXT:    lmg %r13, %r15, 104(%r15)
; CHECK-NEXT:    br %r14
  %r = cmpxchg ptr %p, i8 %c, i8 %n seq_cst seq_cst
  %v = extractvalue { i8, i1 } %r, 0
  ret i8 %v
}

define i64 @strlen_loop(ptr %s) {
; CHECK-LABEL: strlen_loop:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lghi %r1, 0
; CHECK-NEXT:    lgr %r3, %r2
; CHECK-NEXT:    lhi %r0, 0
; CHECK-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    srst %r1, %r3
; CHECK-NEXT:    jo .LBB3_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    sgr %r1, %r2
; CHECK-NEXT:    lgr %r2, %r1
; CHECK-NEXT:    br %r14
  %r = call i64 @strlen(ptr %s)
  ret i64 %r
}

define void @probed_alloca_loop(i64 %n) "probe-stack"="inline-asm" {
; CHECK-LABEL: probed_alloca_loop:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r11, %r15, 88(%r15)
; CHECK-NEXT:    .cfi_offset %r11, -72
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r11, %r15
; CHECK-NEXT:    .cfi_def_cfa_register %r11
; CHECK-NEXT:    la %r1, 7(%r2)
; CHECK-NEXT:    nill %r1, 65528
; CHECK-NEXT:    clgfi %r1, 4096
; CHECK-NEXT:    jl .LBB4_2
; CHECK-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    slgfi %r1, 4096
; CHECK-NEXT:    slgfi %r15, 4096
; CHECK-NEXT:    cg %r15, 4088(%r15)
; CHECK-NEXT:    clgfi %r1, 4096
; CHECK-NEXT:    jhe .LBB4_1
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    cgije %r1, 0, .LBB4_4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    slgr %r15, %r1
; CHECK-NEXT:    cg %r15, -8(%r1,%r15)
; CHECK-NEXT:  .LBB4_4:
; CHECK-NEXT:    la %r2, 160(%r15)
; CHECK-NEXT:    brasl %r14, use@PLT
; CHECK-NEXT:    lmg %r11, %r15, 248(%r11)
; CHECK-NEXT:    br %r14
  %a = alloca i8, i64 %n
  call void @use(ptr %a)
  ret void
}

define void @memcpy_loop(ptr %d, ptr %s, i64 %n) {
; CHECK-LABEL: memcpy_loop:
; CHECK:       # %bb.0:
; CHECK-NEXT:    aghi %r4, -1
; CHECK-NEXT:    cgibe %r4, -1, 0(%r14)
; CHECK-NEXT:  .LBB5_1:
; CHECK-NEXT:    srlg %r0, %r4, 8
; CHECK-NEXT:    cgije %r0, 0, .LBB5_3
; CHECK-NEXT:  .LBB5_2: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    pfd 2, 768(%r2)
; CHECK-NEXT:    mvc 0(256,%r2), 0(%r3)
; CHECK-NEXT:    la %r2, 256(%r2)
; CHECK-NEXT:    la %r3, 256(%r3)
; CHECK-NEXT:    brctg %r0, .LBB5_2
; CHECK-NEXT:  .LBB5_3:
; CHECK-NEXT:    exrl %r4, .Ltmp0
; CHECK-NEXT:    br %r14
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr %s, i64 %n, i1 false)
  ret void
}

define void @memset_loop(ptr %d, i8 %v, i64 %n) {
; CHECK-LABEL: memset_loop:
; CHECK:       # %bb.0:
; CHECK-NEXT:    aghi %r4, -2
; CHECK-NEXT:    cgibe %r4, -2, 0(%r14)
; CHECK-NEXT:  .LBB6_1:
; CHECK-NEXT:    cgije %r4, -1, .LBB6_5
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    srlg %r0, %r4, 8
; CHECK-NEXT:    cgije %r0, 0, .LBB6_4
; CHECK-NEXT:  .LBB6_3: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    pfd 2, 768(%r2)
; CHECK-NEXT:    stc %r3, 0(%r2)
; CHECK-NEXT:    mvc 1(255,%r2), 0(%r2)
; CHECK-NEXT:    la %r2, 256(%r2)
; CHECK-NEXT:    brctg %r0, .LBB6_3
; CHECK-NEXT:  .LBB6_4:
; CHECK-NEXT:    stc %r3, 0(%r2)
; CHECK-NEXT:    exrl %r4, .Ltmp1
; CHECK-NEXT:    br %r14
; CHECK-NEXT:  .LBB6_5:
; CHECK-NEXT:    stc %r3, 0(%r2)
; CHECK-NEXT:    br %r14
  call void @llvm.memset.p0.i64(ptr %d, i8 %v, i64 %n, i1 false)
  ret void
}

declare i64 @strlen(ptr)
declare void @use(ptr)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)
