; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7 -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The select pseudo is expanded by a custom inserter into a diamond with a value
; merge in the sink block. Under -sdag-use-block-args that merge must be a block
; argument fed by SUCC_ARGS, not a machine PHI.
define i32 @select_custom_inserter(i32 %c, i32 %a, i32 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    moveq r1, r2
; CHECK-NEXT:    mov r0, r1
; CHECK-NEXT:    bx lr
  %cmp = icmp ne i32 %c, 0
  %r = select i1 %cmp, i32 %a, i32 %b
  ret i32 %r
}

; A byval struct copy is expanded by a custom inserter into a copy loop whose
; header merges the loop-carried pointers and counter. Those loop-header merges
; must also become block arguments fed by SUCC_ARGS.
%big = type { [64 x i32] }
declare void @callee(ptr byval(%big) %x)
define void @byval_loop_custom_inserter(ptr %p) {
; CHECK-LABEL: byval_loop_custom_inserter:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    push {r4, r5, r11, lr}
; CHECK-NEXT:    sub sp, sp, #240
; CHECK-NEXT:    mov r12, r0
; CHECK-NEXT:    ldr r0, [r0]
; CHECK-NEXT:    ldmib r12, {r1, r2, r3}
; CHECK-NEXT:    add r12, r12, #16
; CHECK-NEXT:    movw lr, #240
; CHECK-NEXT:    mov r4, sp
; CHECK-NEXT:  .LBB1_1: @ =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldr r5, [r12], #4
; CHECK-NEXT:    subs lr, lr, #4
; CHECK-NEXT:    str r5, [r4], #4
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  @ %bb.2:
; CHECK-NEXT:    bl callee
; CHECK-NEXT:    add sp, sp, #240
; CHECK-NEXT:    pop {r4, r5, r11, pc}
  call void @callee(ptr byval(%big) %p)
  ret void
}
