; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=lanai -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through this target's control-flow lowering.

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:       ! %bb.0: ! %entry
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    ld 4[%fp], %r3
; CHECK-NEXT:    ld 0[%fp], %r12
; CHECK-NEXT:    or %r0, 0x0, %r9
; CHECK-NEXT:    bt .LBB0_1
; CHECK-NEXT:    or %r0, 0x0, %r13
; CHECK-NEXT:  .LBB0_3: ! %latch
; CHECK-NEXT:    ! in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    or %r13, 0x0, %r14
; CHECK-NEXT:    add %r14, %r9, %r13
; CHECK-NEXT:    add %r9, 0x1, %r9
; CHECK-NEXT:    sub.f %r9, %r12, %r0
; CHECK-NEXT:    bge .LBB0_4
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_1: ! %loop
; CHECK-NEXT:    ! =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    sub.f %r3, %r9, %r0
; CHECK-NEXT:    bne .LBB0_3
; CHECK-NEXT:    nop
; CHECK-NEXT:  ! %bb.2: ! %then
; CHECK-NEXT:    ! in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    sh %r13, 0x2, %r14
; CHECK-NEXT:    bt .LBB0_3
; CHECK-NEXT:    sub %r14, %r13, %r13
; CHECK-NEXT:  .LBB0_4: ! %exit
; CHECK-NEXT:    add %r14, %r9, %r3
; CHECK-NEXT:    sub %r3, 0x1, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
