; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 -mattr=-nontrapping-fptoint -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The FP-to-int conversion pseudo is expanded by a custom inserter into a diamond
; with a value merge in the join block. Under -sdag-use-block-args that merge
; must be a block argument fed by SUCC_ARGS, not a machine PHI.
define i32 @fptosi_custom_inserter(float %x) {
; CHECK-LABEL: fptosi_custom_inserter:
; CHECK:         .functype fptosi_custom_inserter (f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    block
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    f32.abs
; CHECK-NEXT:    f32.const 0x1p31
; CHECK-NEXT:    f32.lt
; CHECK-NEXT:    i32.eqz
; CHECK-NEXT:    br_if 0 # 0: down to label0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32.trunc_f32_s
; CHECK-NEXT:    return
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    end_block # label0:
; CHECK-NEXT:    i32.const -2147483648
; CHECK-NEXT:    # fallthrough-return
  %r = fptosi float %x to i32
  ret i32 %r
}
