; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mips -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Select pseudos are expanded by custom inserters that merge the true/false
; values in the sink block. Under -sdag-use-block-args those merges must be block
; arguments fed by SUCC_ARGS, not machine PHIs.
define i32 @select_custom_inserter(i32 %c, i32 %a, i32 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movn $6, $5, $4
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    move $2, $6
  %cmp = icmp ne i32 %c, 0
  %r = select i1 %cmp, i32 %a, i32 %b
  ret i32 %r
}

define float @fp_select_custom_inserter(i32 %c, float %a, float %b) {
; CHECK-LABEL: fp_select_custom_inserter:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mtc1 $6, $f0
; CHECK-NEXT:    mtc1 $5, $f1
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    movn.s $f0, $f1, $4
  %cmp = icmp ne i32 %c, 0
  %r = select i1 %cmp, float %a, float %b
  ret float %r
}
