; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+d -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Select pseudos are expanded by a custom inserter that merges the true/false
; values in the tail block. Under -sdag-use-block-args those merges must be block
; arguments fed by SUCC_ARGS, not machine PHIs.
define i64 @select_custom_inserter(i64 %c, i64 %a, i64 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mv a3, a0
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    bnez a3, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    ret
  %cmp = icmp ne i64 %c, 0
  %r = select i1 %cmp, i64 %a, i64 %b
  ret i64 %r
}

; A group of selects with the same condition shares one diamond.
define { i64, i64 } @select_group(i64 %c, i64 %a, i64 %b, i64 %d, i64 %e) {
; CHECK-LABEL: select_group:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mv a5, a0
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    bnez a5, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    mv a3, a4
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    mv a1, a3
; CHECK-NEXT:    ret
  %cmp = icmp ne i64 %c, 0
  %r1 = select i1 %cmp, i64 %a, i64 %b
  %r2 = select i1 %cmp, i64 %d, i64 %e
  %i1 = insertvalue { i64, i64 } undef, i64 %r1, 0
  %i2 = insertvalue { i64, i64 } %i1, i64 %r2, 1
  ret { i64, i64 } %i2
}

; An FP select exercises the Select_FPR merge.
define double @fp_select(double %a, double %b, i1 %c) {
; CHECK-LABEL: fp_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    bnez a0, .LBB2_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    fmv.d fa0, fa1
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    ret
  %r = select i1 %c, double %a, double %b
  ret double %r
}
