; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=loongarch64 -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The select pseudos are expanded by a custom inserter that merges the
; true/false values in the tail block. Under -sdag-use-block-args those merges
; must be block arguments fed by SUCC_ARGS, not machine PHIs.
define i64 @select_custom_inserter(i64 %c, i64 %a, i64 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sltu $a0, $zero, $a0
; CHECK-NEXT:    masknez $a2, $a2, $a0
; CHECK-NEXT:    maskeqz $a0, $a1, $a0
; CHECK-NEXT:    or $a0, $a0, $a2
; CHECK-NEXT:    ret
  %cmp = icmp ne i64 %c, 0
  %r = select i1 %cmp, i64 %a, i64 %b
  ret i64 %r
}

; A group of selects with the same condition shares one diamond.
define { i64, i64 } @select_group(i64 %c, i64 %a, i64 %b, i64 %d, i64 %e) {
; CHECK-LABEL: select_group:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sltu $a5, $zero, $a0
; CHECK-NEXT:    masknez $a0, $a2, $a5
; CHECK-NEXT:    maskeqz $a1, $a1, $a5
; CHECK-NEXT:    or $a0, $a1, $a0
; CHECK-NEXT:    masknez $a1, $a4, $a5
; CHECK-NEXT:    maskeqz $a2, $a3, $a5
; CHECK-NEXT:    or $a1, $a2, $a1
; CHECK-NEXT:    ret
  %cmp = icmp ne i64 %c, 0
  %r1 = select i1 %cmp, i64 %a, i64 %b
  %r2 = select i1 %cmp, i64 %d, i64 %e
  %i1 = insertvalue { i64, i64 } undef, i64 %r1, 0
  %i2 = insertvalue { i64, i64 } %i1, i64 %r2, 1
  ret { i64, i64 } %i2
}
