; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-- -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The F128CSEL pseudo is expanded by a custom inserter into a diamond with a
; value merge in the join block. Under -sdag-use-block-args that merge must be a
; block argument fed by SUCC_ARGS, not a machine PHI.
define fp128 @f128_select(i1 %c, fp128 %a, fp128 %b) {
; CHECK-LABEL: f128_select:
; CHECK:       // %bb.0:
; CHECK-NEXT:    tst w0, #0x1
; CHECK-NEXT:    b.eq .LBB0_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov v1.16b, v0.16b
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    mov v0.16b, v1.16b
; CHECK-NEXT:    ret
  %r = select i1 %c, fp128 %a, fp128 %b
  ret fp128 %r
}
