; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=aarch64 < %s | FileCheck %s

; Early if-conversion of a diamond whose tail carries multiple block arguments.
; Head gains a new edge to the tail, so its SUCC_ARGS is built incrementally as
; the arguments are processed in ascending index order. A tail with two block
; arguments (and a third tail predecessor keeping them live) exercises appending
; the second operand rather than indexing past the freshly built SUCC_ARGS. The
; block-args output must match the default PHI-lowering path.

define void @diamond_two_block_args(ptr %p0, ptr %p1, i32 %c, i64 %a, i64 %b, i64 %e, i64 %g, i1 %extra) {
; CHECK-LABEL: diamond_two_block_args:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    add x8, x4, #3
; CHECK-NEXT:    add x9, x3, #4
; CHECK-NEXT:    add x10, x4, #2
; CHECK-NEXT:    cmp w2, #0
; CHECK-NEXT:    csinc x8, x8, x3, ne
; CHECK-NEXT:    csel x9, x9, x10, ne
; CHECK-NEXT:    tst w7, #0x1
; CHECK-NEXT:    csel x8, x5, x8, eq
; CHECK-NEXT:    csel x9, x6, x9, eq
; CHECK-NEXT:    str x8, [x0]
; CHECK-NEXT:    str x9, [x1]
; CHECK-NEXT:    ret
entry:
  %cmp = icmp eq i32 %c, 0
  br i1 %extra, label %pre, label %tail
pre:
  br i1 %cmp, label %tb, label %fb
tb:
  %t0 = add i64 %a, 1
  %t1 = add i64 %b, 2
  br label %tail
fb:
  %f0 = add i64 %b, 3
  %f1 = add i64 %a, 4
  br label %tail
tail:
  %x = phi i64 [ %t0, %tb ], [ %f0, %fb ], [ %e, %entry ]
  %y = phi i64 [ %t1, %tb ], [ %f1, %fb ], [ %g, %entry ]
  store i64 %x, ptr %p0
  store i64 %y, ptr %p1
  ret void
}
