; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=aarch64 < %s | FileCheck %s

; Early if-conversion must fold a merge value that reaches the tail as a block
; argument (SUCC_ARGS feeder) into a branchless select, just as it does for a
; PHI. Both nested triangles collapse into a csel/csinc pair with no branches,
; identically to the PHI (non-block-args) path.

define void @early_ifcvt_block_arg(ptr %dst, i1 %0, i1 %cmp) {
; CHECK-LABEL: early_ifcvt_block_arg:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    tst w2, #0x1
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:    tst w1, #0x1
; CHECK-NEXT:    csinc x8, x8, xzr, ne
; CHECK-NEXT:    str x8, [x0]
; CHECK-NEXT:    ret
entry:
  br i1 %0, label %then, label %exit

then:
  call void @llvm.donothing()
  br i1 %cmp, label %true, label %exit

true:
  call void @llvm.donothing()
  br label %exit

exit:
  %x = phi i64 [ 0, %true ], [ 0, %then ], [ 1, %entry ]
  store i64 %x, ptr %dst, align 8
  ret void
}

declare void @llvm.donothing()
