; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -mcpu=cortex-a57 -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=aarch64-linux-gnu -mcpu=cortex-a57 < %s | FileCheck %s

; MachineSinking must treat a SUCC_ARGS operand as an on-edge use so it splits
; the critical edge and sinks the copy, matching the PHI path: a single cbz with
; no save copy of the tested value.

define i64 @f_XX(i64 %n, ptr nocapture readonly %P) {
; CHECK-LABEL: f_XX:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cbz x0, .LBB0_2
; CHECK-NEXT:  // %bb.1: // %if.then
; CHECK-NEXT:    ldr x0, [x1]
; CHECK-NEXT:  .LBB0_2: // %if.end
; CHECK-NEXT:    ret
entry:
  %tobool = icmp eq i64 %n, 0
  br i1 %tobool, label %if.end, label %if.then

if.then:
  %0 = load i64, ptr %P
  br label %if.end

if.end:
  %a.0 = phi i64 [ %0, %if.then ], [ 0, %entry ]
  ret i64 %a.0
}
