; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ve -sdag-use-block-args -stop-after=finalize-isel < %s | FileCheck %s

; The SjLj setjmp pseudo is expanded by a custom inserter into a diamond whose
; merge feeds the sink block. Under -sdag-use-block-args that merge must be a
; block argument fed by SUCC_ARGS, not a machine PHI. (-verify-machineinstrs is
; not used here: this lowering trips a pre-existing LEAzii register-class error
; unrelated to block arguments.)
declare i32 @llvm.eh.sjlj.setjmp(ptr)
define i32 @sjlj_custom_inserter(ptr %buf) {
  ; CHECK-LABEL: name: sjlj_custom_inserter
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $sx0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:i64 = COPY $sx0
  ; CHECK-NEXT:   [[LEAzii:%[0-9]+]]:i64 = LEAzii 0, 0, target-flags(<unknown>) %bb.3
  ; CHECK-NEXT:   [[ANDrm:%[0-9]+]]:i64 = ANDrm killed [[LEAzii]], 96
  ; CHECK-NEXT:   [[LEASLrii:%[0-9]+]]:i64 = LEASLrii killed [[ANDrm]], 0, target-flags(<unknown>) %bb.3
  ; CHECK-NEXT:   STrii [[COPY]], 0, 8, killed [[LEASLrii]]
  ; CHECK-NEXT:   EH_SjLj_Setup %bb.3, csr_noregs
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LEAzii1:%[0-9]+]]:i32 = LEAzii 0, 0, 0
  ; CHECK-NEXT:   SUCC_ARGS %bb.2, [[LEAzii1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (%ir-block.0):
  ; CHECK-NEXT:   arguments: %1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i64 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[INSERT_SUBREG:%[0-9]+]]:i64 = INSERT_SUBREG [[DEF]], killed %1:i32, %subreg.sub_i32
  ; CHECK-NEXT:   $sx0 = COPY [[INSERT_SUBREG]]
  ; CHECK-NEXT:   RET implicit $sx10, implicit $sx0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3 (%ir-block.0, machine-block-address-taken):
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LEAzii2:%[0-9]+]]:i32 = LEAzii 0, 0, 1
  ; CHECK-NEXT:   SUCC_ARGS %bb.2, [[LEAzii2]]
  ; CHECK-NEXT:   BRCFLa_t %bb.2
  %r = call i32 @llvm.eh.sjlj.setjmp(ptr %buf)
  ret i32 %r
}
