; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=m68k -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; The CMOV pseudo is expanded by a custom inserter into a diamond with a value
; merge in the sink block. Under -sdag-use-block-args that merge must be a block
; argument fed by SUCC_ARGS, not a machine PHI.
define i32 @select_custom_inserter(i32 %c, i32 %a, i32 %b) {
; CHECK-LABEL: select_custom_inserter:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    move.l (4,%sp), %d0
; CHECK-NEXT:    cmpi.l #0, %d0
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    lea (12,%sp), %a0
; CHECK-NEXT:    move.l (%a0), %d0
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    lea (8,%sp), %a0
; CHECK-NEXT:    move.l (%a0), %d0
; CHECK-NEXT:    rts
  %cmp = icmp ne i32 %c, 0
  %r = select i1 %cmp, i32 %a, i32 %b
  ret i32 %r
}

; A cascaded select exercises the second-Jcc merge operand.
define i32 @cascaded_select(i32 %x, i32 %a, i32 %b) {
; CHECK-LABEL: cascaded_select:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    suba.l #4, %sp
; CHECK-NEXT:    .cfi_def_cfa_offset -8
; CHECK-NEXT:    movem.l %d2, (0,%sp) ; 8-byte Folded Spill
; CHECK-NEXT:    move.l (16,%sp), %d1
; CHECK-NEXT:    move.l (8,%sp), %d2
; CHECK-NEXT:    cmpi.l #0, %d2
; CHECK-NEXT:    beq .LBB1_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    move.l %d1, %d0
; CHECK-NEXT:    cmpi.l #1, %d2
; CHECK-NEXT:    beq .LBB1_5
; CHECK-NEXT:    bra .LBB1_4
; CHECK-NEXT:  .LBB1_1:
; CHECK-NEXT:    move.l (12,%sp), %d0
; CHECK-NEXT:    cmpi.l #1, %d2
; CHECK-NEXT:    beq .LBB1_5
; CHECK-NEXT:  .LBB1_4:
; CHECK-NEXT:    move.l %d1, %d0
; CHECK-NEXT:  .LBB1_5:
; CHECK-NEXT:    movem.l (0,%sp), %d2 ; 8-byte Folded Reload
; CHECK-NEXT:    adda.l #4, %sp
; CHECK-NEXT:    rts
  %c1 = icmp eq i32 %x, 0
  %c2 = icmp eq i32 %x, 1
  %s1 = select i1 %c1, i32 %a, i32 %b
  %r = select i1 %c2, i32 %s1, i32 %b
  ret i32 %r
}
