; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=m68k -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through this target's control-flow lowering.

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    suba.l #8, %sp
; CHECK-NEXT:    .cfi_def_cfa_offset -12
; CHECK-NEXT:    movem.l %d2-%d3, (0,%sp) ; 12-byte Folded Spill
; CHECK-NEXT:    moveq #0, %d3
; CHECK-NEXT:    move.l (16,%sp), %d2
; CHECK-NEXT:    move.l (12,%sp), %a0
; CHECK-NEXT:    move.l %d3, %d1
; CHECK-NEXT:    bra .LBB0_1
; CHECK-NEXT:  .LBB0_3: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    move.l %d3, %d0
; CHECK-NEXT:    add.l %d1, %d3
; CHECK-NEXT:    add.l #1, %d1
; CHECK-NEXT:    cmp.l %a0, %d1
; CHECK-NEXT:    bge .LBB0_4
; CHECK-NEXT:  .LBB0_1: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmp.l %d1, %d2
; CHECK-NEXT:    bne .LBB0_3
; CHECK-NEXT:  ; %bb.2: ; %then
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    move.l %d3, %d0
; CHECK-NEXT:    lsl.l #1, %d0
; CHECK-NEXT:    add.l %d3, %d0
; CHECK-NEXT:    move.l %d0, %d3
; CHECK-NEXT:    bra .LBB0_3
; CHECK-NEXT:  .LBB0_4: ; %exit
; CHECK-NEXT:    add.l %d1, %d0
; CHECK-NEXT:    add.l #-1, %d0
; CHECK-NEXT:    movem.l (0,%sp), %d2-%d3 ; 12-byte Folded Reload
; CHECK-NEXT:    adda.l #8, %sp
; CHECK-NEXT:    rts
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
