; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -passes='instcombine<max-iterations=1>' %s | FileCheck %s

; This would previously fail to reach a fixed point after 1 iteration.
define void @issue68120_worklist_issue(ptr align 8 %arg) {
; CHECK-LABEL: define void @issue68120_worklist_issue(
; CHECK-SAME: ptr align 8 [[ARG:%.*]]) {
; CHECK-NEXT:    store ptr poison, ptr null, align 8
; CHECK-NEXT:    ret void
;
  %alloca = alloca ptr, align 8, addrspace(5)
  %addrspacecast = addrspacecast ptr addrspace(5) %alloca to ptr
  store ptr %arg, ptr %addrspacecast, align 8
  %reload = load ptr, ptr %addrspacecast, align 8
  store ptr %reload, ptr null, align 8
  ret void
}

; store instruction sees a non-0 GEP instead of the direct addrspacecast(alloca)
define void @issue68120_worklist_issue_with_gep(ptr align 8 %arg) {
; CHECK-LABEL: define void @issue68120_worklist_issue_with_gep(
; CHECK-SAME: ptr align 8 [[ARG:%.*]]) {
; CHECK-NEXT:    store ptr poison, ptr null, align 8
; CHECK-NEXT:    ret void
;
  %alloca = alloca [16 x ptr], align 8, addrspace(5)
  %addrspacecast = addrspacecast ptr addrspace(5) %alloca to ptr
  %gep = getelementptr [16 x ptr], ptr %addrspacecast, i64 0, i64 3
  store ptr %arg, ptr %gep, align 8
  %reload = load ptr, ptr %addrspacecast, align 8
  store ptr %reload, ptr null, align 8
  ret void
}

; There is a second use of the stripped pointer, but not the original value
define void @issue68120_worklist_issue_second_use_after_ptr_strip(ptr align 8 %arg, ptr align 8 %arg1) {
; CHECK-LABEL: define void @issue68120_worklist_issue_second_use_after_ptr_strip(
; CHECK-SAME: ptr align 8 [[ARG:%.*]], ptr align 8 [[ARG1:%.*]]) {
; CHECK-NEXT:    store ptr poison, ptr null, align 8
; CHECK-NEXT:    ret void
;
  %alloca = alloca ptr, align 8, addrspace(5)
  store ptr %arg1, ptr addrspace(5) %alloca
  %addrspacecast = addrspacecast ptr addrspace(5) %alloca to ptr
  store ptr %arg, ptr %addrspacecast, align 8
  %reload = load ptr, ptr %addrspacecast, align 8
  store ptr %reload, ptr null, align 8
  ret void
}

define void @issue68120_worklist_issue_with_gep_multi_use(ptr align 8 %arg, ptr align 8 %arg1) {
; CHECK-LABEL: define void @issue68120_worklist_issue_with_gep_multi_use(
; CHECK-SAME: ptr align 8 [[ARG:%.*]], ptr align 8 [[ARG1:%.*]]) {
; CHECK-NEXT:    store ptr poison, ptr null, align 8
; CHECK-NEXT:    ret void
;
  %alloca = alloca [16 x ptr], align 8, addrspace(5)
  store ptr %arg1, ptr addrspace(5) %alloca
  %addrspacecast = addrspacecast ptr addrspace(5) %alloca to ptr
  %gep = getelementptr [16 x ptr], ptr %addrspacecast, i64 0, i64 3
  store ptr %arg, ptr %gep, align 8
  %reload = load ptr, ptr %addrspacecast, align 8
  store ptr %reload, ptr null, align 8
  ret void
}
