; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=msp430 -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through this target's control-flow lowering.

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    push r4
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    push r5
; CHECK-NEXT:    .cfi_def_cfa_offset 6
; CHECK-NEXT:    push r6
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    push r7
; CHECK-NEXT:    .cfi_def_cfa_offset 10
; CHECK-NEXT:    push r8
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    push r9
; CHECK-NEXT:    .cfi_def_cfa_offset 14
; CHECK-NEXT:    push r10
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sub #2, r1
; CHECK-NEXT:    .cfi_def_cfa_offset 18
; CHECK-NEXT:    .cfi_offset r4, -4
; CHECK-NEXT:    .cfi_offset r5, -6
; CHECK-NEXT:    .cfi_offset r6, -8
; CHECK-NEXT:    .cfi_offset r7, -10
; CHECK-NEXT:    .cfi_offset r8, -12
; CHECK-NEXT:    .cfi_offset r9, -14
; CHECK-NEXT:    .cfi_offset r10, -16
; CHECK-NEXT:    mov r15, 0(r1) ; 2-byte Folded Spill
; CHECK-NEXT:    mov r14, r9
; CHECK-NEXT:    mov r13, r8
; CHECK-NEXT:    mov r12, r7
; CHECK-NEXT:    clr r6
; CHECK-NEXT:    clr r5
; CHECK-NEXT:    clr r12
; CHECK-NEXT:    clr r13
; CHECK-NEXT:    jmp .LBB0_2
; CHECK-NEXT:  .LBB0_1: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    add r5, r13
; CHECK-NEXT:    mov r6, r14
; CHECK-NEXT:    add r12, r14
; CHECK-NEXT:    cmp r12, r14
; CHECK-NEXT:    bic r2, r4
; CHECK-NEXT:    add r4, r13
; CHECK-NEXT:    bit #1, r10
; CHECK-NEXT:    mov r15, r6
; CHECK-NEXT:    mov r11, r5
; CHECK-NEXT:    mov r14, r12
; CHECK-NEXT:    jeq .LBB0_8
; CHECK-NEXT:  .LBB0_2: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov r6, r14
; CHECK-NEXT:    xor r9, r14
; CHECK-NEXT:    mov r5, r15
; CHECK-NEXT:    mov 0(r1), r11 ; 2-byte Folded Reload
; CHECK-NEXT:    xor r11, r15
; CHECK-NEXT:    bis r14, r15
; CHECK-NEXT:    tst r15
; CHECK-NEXT:    jne .LBB0_4
; CHECK-NEXT:  ; %bb.3: ; %then
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    mov #3, r14
; CHECK-NEXT:    clr r15
; CHECK-NEXT:    call #__mspabi_mpyl
; CHECK-NEXT:  .LBB0_4: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    mov r6, r15
; CHECK-NEXT:    inc r15
; CHECK-NEXT:    cmp r7, r15
; CHECK-NEXT:    mov r2, r14
; CHECK-NEXT:    tst r15
; CHECK-NEXT:    mov r2, r11
; CHECK-NEXT:    rra r11
; CHECK-NEXT:    and #1, r11
; CHECK-NEXT:    add r5, r11
; CHECK-NEXT:    mov #1, r4
; CHECK-NEXT:    cmp r8, r11
; CHECK-NEXT:    mov #1, r10
; CHECK-NEXT:    jl .LBB0_6
; CHECK-NEXT:  ; %bb.5: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    clr r10
; CHECK-NEXT:  .LBB0_6: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    cmp r8, r11
; CHECK-NEXT:    jne .LBB0_1
; CHECK-NEXT:  ; %bb.7: ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    mov #1, r10
; CHECK-NEXT:    bic r14, r10
; CHECK-NEXT:    jmp .LBB0_1
; CHECK-NEXT:  .LBB0_8: ; %exit
; CHECK-NEXT:    mov r14, r12
; CHECK-NEXT:    add #2, r1
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pop r10
; CHECK-NEXT:    .cfi_def_cfa_offset 14
; CHECK-NEXT:    pop r9
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    pop r8
; CHECK-NEXT:    .cfi_def_cfa_offset 10
; CHECK-NEXT:    pop r7
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    pop r6
; CHECK-NEXT:    .cfi_def_cfa_offset 6
; CHECK-NEXT:    pop r5
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    pop r4
; CHECK-NEXT:    .cfi_def_cfa_offset 2
; CHECK-NEXT:    .cfi_restore r4
; CHECK-NEXT:    .cfi_restore r5
; CHECK-NEXT:    .cfi_restore r6
; CHECK-NEXT:    .cfi_restore r7
; CHECK-NEXT:    .cfi_restore r8
; CHECK-NEXT:    .cfi_restore r9
; CHECK-NEXT:    .cfi_restore r10
; CHECK-NEXT:    ret
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
