; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=csky -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through this target's control-flow lowering.

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subi16 sp, sp, 4
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    st16.w l0, (sp, 0) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset l0, -4
; CHECK-NEXT:    subi16 sp, sp, 4
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    movi16 a3, 0
; CHECK-NEXT:    movi16 a2, 0
; CHECK-NEXT:    br32 .LBB0_3
; CHECK-NEXT:  .LBB0_1: # %then
; CHECK-NEXT:    # in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    lsli16 l0, a3, 1
; CHECK-NEXT:    addu16 l0, l0, a3
; CHECK-NEXT:  .LBB0_2: # %latch
; CHECK-NEXT:    # in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    addu16 a3, l0, a2
; CHECK-NEXT:    addi16 a2, 1
; CHECK-NEXT:    cmplt16 a2, a0
; CHECK-NEXT:    bf16 .LBB0_5
; CHECK-NEXT:  .LBB0_3: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmpne16 a1, a2
; CHECK-NEXT:    bf16 .LBB0_1
; CHECK-NEXT:  # %bb.4: # in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    mov16 l0, a3
; CHECK-NEXT:    br32 .LBB0_2
; CHECK-NEXT:  .LBB0_5: # %exit
; CHECK-NEXT:    addu16 a0, l0, a2
; CHECK-NEXT:    subi16 a0, 1
; CHECK-NEXT:    addi16 sp, sp, 4
; CHECK-NEXT:    ld16.w l0, (sp, 0) # 4-byte Folded Reload
; CHECK-NEXT:    addi16 sp, sp, 4
; CHECK-NEXT:    rts16
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
