; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=avr -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Exercise the block-arguments lowering path (PHIs represented as block
; arguments fed by SUCC_ARGS) through this target's control-flow lowering.

define i32 @loop_diamond(i32 %n, i32 %x) {
; CHECK-LABEL: loop_diamond:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    push r2
; CHECK-NEXT:    push r3
; CHECK-NEXT:    push r4
; CHECK-NEXT:    push r5
; CHECK-NEXT:    push r6
; CHECK-NEXT:    push r7
; CHECK-NEXT:    push r8
; CHECK-NEXT:    push r9
; CHECK-NEXT:    push r10
; CHECK-NEXT:    push r11
; CHECK-NEXT:    push r12
; CHECK-NEXT:    push r13
; CHECK-NEXT:    push r14
; CHECK-NEXT:    push r15
; CHECK-NEXT:    push r16
; CHECK-NEXT:    push r17
; CHECK-NEXT:    mov r8, r20
; CHECK-NEXT:    mov r9, r21
; CHECK-NEXT:    mov r14, r18
; CHECK-NEXT:    mov r15, r19
; CHECK-NEXT:    mov r12, r24
; CHECK-NEXT:    mov r13, r25
; CHECK-NEXT:    mov r10, r22
; CHECK-NEXT:    mov r11, r23
; CHECK-NEXT:    ldi r24, 0
; CHECK-NEXT:    ldi r25, 0
; CHECK-NEXT:    ldi r18, 3
; CHECK-NEXT:    ldi r19, 0
; CHECK-NEXT:    mov r4, r18
; CHECK-NEXT:    mov r5, r19
; CHECK-NEXT:    mov r20, r24
; CHECK-NEXT:    mov r21, r25
; CHECK-NEXT:    mov r16, r24
; CHECK-NEXT:    mov r17, r25
; CHECK-NEXT:    mov r22, r24
; CHECK-NEXT:    mov r23, r25
; CHECK-NEXT:    mov r6, r24
; CHECK-NEXT:    mov r7, r25
; CHECK-NEXT:    rjmp .LBB0_2
; CHECK-NEXT:  .LBB0_1: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    andi r18, 1
; CHECK-NEXT:    cpi r18, 0
; CHECK-NEXT:    brne .LBB0_2
; CHECK-NEXT:    rjmp .LBB0_8
; CHECK-NEXT:  .LBB0_2: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldi r18, 1
; CHECK-NEXT:    cp r20, r14
; CHECK-NEXT:    cpc r21, r15
; CHECK-NEXT:    cpc r16, r8
; CHECK-NEXT:    cpc r17, r9
; CHECK-NEXT:    brne .LBB0_4
; CHECK-NEXT:  ; %bb.3: ; %loop
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    mov r18, r1
; CHECK-NEXT:  .LBB0_4: ; %loop
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    andi r18, 1
; CHECK-NEXT:    cpi r18, 0
; CHECK-NEXT:    brne .LBB0_6
; CHECK-NEXT:  ; %bb.5: ; %then
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    mov r18, r4
; CHECK-NEXT:    mov r19, r5
; CHECK-NEXT:    mov r2, r20
; CHECK-NEXT:    mov r3, r21
; CHECK-NEXT:    mov r20, r6
; CHECK-NEXT:    mov r21, r7
; CHECK-NEXT:    rcall __mulsi3
; CHECK-NEXT:    mov r20, r2
; CHECK-NEXT:    mov r21, r3
; CHECK-NEXT:  .LBB0_6: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    add r22, r20
; CHECK-NEXT:    adc r23, r21
; CHECK-NEXT:    adc r24, r16
; CHECK-NEXT:    adc r25, r17
; CHECK-NEXT:    subi r20, 255
; CHECK-NEXT:    sbci r21, 255
; CHECK-NEXT:    sbci r16, 255
; CHECK-NEXT:    sbci r17, 255
; CHECK-NEXT:    ldi r18, 1
; CHECK-NEXT:    cp r20, r10
; CHECK-NEXT:    cpc r21, r11
; CHECK-NEXT:    cpc r16, r12
; CHECK-NEXT:    cpc r17, r13
; CHECK-NEXT:    brge .LBB0_7
; CHECK-NEXT:    rjmp .LBB0_1
; CHECK-NEXT:  .LBB0_7: ; %latch
; CHECK-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    mov r18, r1
; CHECK-NEXT:    rjmp .LBB0_1
; CHECK-NEXT:  .LBB0_8: ; %exit
; CHECK-NEXT:    pop r17
; CHECK-NEXT:    pop r16
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    pop r14
; CHECK-NEXT:    pop r13
; CHECK-NEXT:    pop r12
; CHECK-NEXT:    pop r11
; CHECK-NEXT:    pop r10
; CHECK-NEXT:    pop r9
; CHECK-NEXT:    pop r8
; CHECK-NEXT:    pop r7
; CHECK-NEXT:    pop r6
; CHECK-NEXT:    pop r5
; CHECK-NEXT:    pop r4
; CHECK-NEXT:    pop r3
; CHECK-NEXT:    pop r2
; CHECK-NEXT:    ret
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %cmp = icmp eq i32 %i, %x
  br i1 %cmp, label %then, label %latch

then:
  %scaled = mul i32 %acc, 3
  br label %latch

latch:
  %merged = phi i32 [ %scaled, %then ], [ %acc, %loop ]
  %acc.next = add i32 %merged, %i
  %i.next = add i32 %i, 1
  %done = icmp slt i32 %i.next, %n
  br i1 %done, label %loop, label %exit

exit:
  ret i32 %acc.next
}
