; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -sdag-use-block-args -stop-after=x86-slh -o - %s | FileCheck %s

; Speculative load hardening splits the critical latch edge into the loop header
; bb.2, which carries a block argument. The SUCC_ARGS forwarding the loop-carried
; value along that edge must move out of the header and into the newly inserted
; block (bb.5 below), so bb.2 still receives its argument from every predecessor
; edge, with exactly one SUCC_ARGS per predecessor.

define void @test_basic_loop(i32 %a, i32 %b, ptr %ptr1, ptr %ptr2) nounwind speculative_load_hardening {
  ; CHECK-LABEL: name: test_basic_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x30000000), %bb.4(0x50000000)
  ; CHECK-NEXT:   liveins: $edi, $esi, $rdx, $rcx
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV64ri32_:%[0-9]+]]:gr64_nosp = MOV64ri32 -1
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr64_nosp = COPY $rsp
  ; CHECK-NEXT:   [[SAR64ri:%[0-9]+]]:gr64_nosp = SAR64ri killed [[COPY]], 63, implicit-def dead $eflags
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64 = COPY $rcx
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gr64 = COPY $rdx
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gr32 = COPY $esi
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gr32 = COPY $edi
  ; CHECK-NEXT:   TEST32rr [[COPY4]], [[COPY4]], implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.4, 5, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CMOV64rr:%[0-9]+]]:gr64_nosp = CMOV64rr [[SAR64ri]], [[MOV64ri32_]], 4, implicit killed $eflags
  ; CHECK-NEXT:   JMP_1 %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.l.header.preheader:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CMOV64rr1:%[0-9]+]]:gr64_nosp = CMOV64rr [[SAR64ri]], [[MOV64ri32_]], 5, implicit killed $eflags
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   SUCC_ARGS %bb.2, [[MOV32r0_]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.l.header:
  ; CHECK-NEXT:   successors: %bb.5(0x7c000000), %bb.6(0x04000000)
  ; CHECK-NEXT:   arguments: %0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gr64_nosp = PHI [[CMOV64rr1]], %bb.1, %15, %bb.5
  ; CHECK-NEXT:   [[MOVSX64rm32_:%[0-9]+]]:gr64_nosp = MOVSX64rm32 [[COPY2]], 1, $noreg, 0, $noreg :: (load (s32) from %ir.ptr1)
  ; CHECK-NEXT:   [[OR64rr:%[0-9]+]]:gr64_nosp = OR64rr [[PHI]], [[MOVSX64rm32_]], implicit-def dead $eflags
  ; CHECK-NEXT:   [[OR64rr1:%[0-9]+]]:gr64 = OR64rr [[PHI]], [[COPY1]], implicit-def dead $eflags
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm [[OR64rr1]], 4, killed [[OR64rr]], 0, $noreg :: (load (s32) from %ir.ptr2.idx)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   $edi = COPY [[MOV32rm]]
  ; CHECK-NEXT:   [[SHL64ri:%[0-9]+]]:gr64_nosp = SHL64ri killed [[PHI]], 47, implicit-def dead $eflags
  ; CHECK-NEXT:   $rsp = OR64rr $rsp, killed [[SHL64ri]], implicit-def dead $eflags
  ; CHECK-NEXT:   CALL64pcrel32 target-flags(x86-plt) @sink, csr_64, implicit $rsp, implicit $ssp, implicit $edi, implicit-def $rsp, implicit-def $ssp, post-instr-symbol <mcsymbol >
  ; CHECK-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm $rsp, 1, $noreg, -8, $noreg
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gr64_nosp = COPY $rsp
  ; CHECK-NEXT:   [[SAR64ri1:%[0-9]+]]:gr64_nosp = SAR64ri killed [[COPY5]], 63, implicit-def dead $eflags
  ; CHECK-NEXT:   CMP64ri32 killed [[MOV64rm]], <mcsymbol >, implicit-def $eflags
  ; CHECK-NEXT:   [[CMOV64rr2:%[0-9]+]]:gr64_nosp = CMOV64rr killed [[SAR64ri1]], [[MOV64ri32_]], 5, implicit killed $eflags
  ; CHECK-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   [[INC32r:%[0-9]+]]:gr32 = INC32r %0:gr32, implicit-def dead $eflags
  ; CHECK-NEXT:   CMP32rr [[INC32r]], [[COPY3]], implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.5, 12, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CMOV64rr3:%[0-9]+]]:gr64_nosp = CMOV64rr [[CMOV64rr2]], [[MOV64ri32_]], 12, implicit killed $eflags
  ; CHECK-NEXT:   JMP_1 %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CMOV64rr4:%[0-9]+]]:gr64_nosp = CMOV64rr [[CMOV64rr2]], [[MOV64ri32_]], 13, implicit killed $eflags
  ; CHECK-NEXT:   SUCC_ARGS %bb.2, [[INC32r]]
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.exit:
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gr64_nosp = PHI [[CMOV64rr]], %bb.4, [[CMOV64rr3]], %bb.6
  ; CHECK-NEXT:   [[SHL64ri1:%[0-9]+]]:gr64_nosp = SHL64ri killed [[PHI1]], 47, implicit-def dead $eflags
  ; CHECK-NEXT:   $rsp = OR64rr $rsp, killed [[SHL64ri1]], implicit-def dead $eflags
  ; CHECK-NEXT:   RET 0
entry:
  %a.cmp = icmp eq i32 %a, 0
  br i1 %a.cmp, label %l.header, label %exit

l.header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %l.header ]
  %secret = load i32, ptr %ptr1
  %ptr2.idx = getelementptr i32, ptr %ptr2, i32 %secret
  %leak = load i32, ptr %ptr2.idx
  call void @sink(i32 %leak)
  %i.next = add i32 %i, 1
  %i.cmp = icmp slt i32 %i.next, %b
  br i1 %i.cmp, label %l.header, label %exit

exit:
  ret void
}

declare void @sink(i32)
