; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-- -mattr=+rtm -sdag-use-block-args -verify-machineinstrs < %s | FileCheck %s

; Custom inserters (EmitInstrWithCustomInserter) build value merges directly.
; Under -sdag-use-block-args those merges must be block arguments fed by
; SUCC_ARGS, not machine PHIs.

; An FP select is expanded via the CMOV_* pseudo, whose inserter merges the
; true/false values in the sink block. Forwarding a value from the block that
; held the CMOV must not disturb the pseudo-removal range.
define double @fp_select(i1 %c, double %a, double %b) {
; CHECK-LABEL: fp_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    jne .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    movaps %xmm1, %xmm0
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    retq
  %r = select i1 %c, double %a, double %b
  ret double %r
}

; A group of FP selects with the same condition shares one diamond; each merge
; forwards a value from the same true/false blocks.
define { double, double } @fp_select_group(i1 %c, double %a, double %b,
; CHECK-LABEL: fp_select_group:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    jne .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    movaps %xmm1, %xmm0
; CHECK-NEXT:    movaps %xmm3, %xmm2
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    movaps %xmm2, %xmm1
; CHECK-NEXT:    retq
                                           double %d, double %e) {
  %r1 = select i1 %c, double %a, double %b
  %r2 = select i1 %c, double %d, double %e
  %i1 = insertvalue { double, double } undef, double %r1, 0
  %i2 = insertvalue { double, double } %i1, double %r2, 1
  ret { double, double } %i2
}

; va_arg lowering merges the register-save and overflow paths in its join block.
define i32 @vaarg(ptr %va) {
; CHECK-LABEL: vaarg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl (%rdi), %ecx
; CHECK-NEXT:    cmpl $48, %ecx
; CHECK-NEXT:    jae .LBB2_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    movq 16(%rdi), %rax
; CHECK-NEXT:    addq %rcx, %rax
; CHECK-NEXT:    addl $8, %ecx
; CHECK-NEXT:    movl %ecx, (%rdi)
; CHECK-NEXT:    movl (%rax), %eax
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    movq 8(%rdi), %rax
; CHECK-NEXT:    movq %rax, %rcx
; CHECK-NEXT:    addq $8, %rcx
; CHECK-NEXT:    movq %rcx, 8(%rdi)
; CHECK-NEXT:    movl (%rax), %eax
; CHECK-NEXT:    retq
  %r = va_arg ptr %va, i32
  ret i32 %r
}

; The xbegin RTM intrinsic merges the fallthrough and abort paths.
declare i32 @llvm.x86.xbegin()
define i32 @xbegin() {
; CHECK-LABEL: xbegin:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xbegin .LBB3_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    movl $-1, %eax
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    # XABORT DEF
; CHECK-NEXT:    retq
  %r = call i32 @llvm.x86.xbegin()
  ret i32 %r
}

; SjLj setjmp merges the setup and restore (address-taken) paths. The restore
; block's SUCC_ARGS must land in the terminator-adjacent cluster.
declare i32 @llvm.eh.sjlj.setjmp(ptr)
define i32 @sjlj(ptr %buf) {
; CHECK-LABEL: sjlj:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movq $.LBB4_3, 8(%rdi)
; CHECK-NEXT:    #EH_SjLj_Setup .LBB4_3
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    jmp .LBB4_2
; CHECK-NEXT:  .LBB4_3: # Block address taken
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call i32 @llvm.eh.sjlj.setjmp(ptr %buf)
  ret i32 %r
}

; An inline stack probe for a dynamic alloca merges the probe-loop result.
define void @probed_alloca(i64 %n) "probe-stack"="inline-asm" {
; CHECK-LABEL: probed_alloca:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movq %rsp, %rbp
; CHECK-NEXT:    .cfi_def_cfa_register %rbp
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    movq %rsp, %rdi
; CHECK-NEXT:    addq $15, %rax
; CHECK-NEXT:    andq $-16, %rax
; CHECK-NEXT:    subq %rax, %rdi
; CHECK-NEXT:    cmpq %rsp, %rdi
; CHECK-NEXT:    jae .LBB5_3
; CHECK-NEXT:  .LBB5_2: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    xorq $0, (%rsp)
; CHECK-NEXT:    subq $4096, %rsp # imm = 0x1000
; CHECK-NEXT:    cmpq %rsp, %rdi
; CHECK-NEXT:    jb .LBB5_2
; CHECK-NEXT:  .LBB5_3:
; CHECK-NEXT:    movq %rdi, %rsp
; CHECK-NEXT:    callq use@PLT
; CHECK-NEXT:    movq %rbp, %rsp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa %rsp, 8
; CHECK-NEXT:    retq
  %a = alloca i8, i64 %n
  call void @use(ptr %a)
  ret void
}
declare void @use(ptr)
