; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs -early-live-intervals < %s | FileCheck %s

; A gc.relocate of a constant in an invoke's landing pad must materialize the
; constant in the landing pad, not export a vreg defined after the statepoint
; call in the invoke block. Such a def does not dominate the use reached by the
; unwind edge, producing an invalid live range once LiveIntervals is computed
; before TwoAddressInstruction.

target triple = "x86_64-pc-linux-gnu"

define ptr addrspace(1) @relocate_constant_in_landing_pad() gc "statepoint-example" personality ptr null {
; CHECK-LABEL: relocate_constant_in_landing_pad:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:  .Ltmp0: # EH_LABEL
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    callq *%rax
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:  .Ltmp1: # EH_LABEL
; CHECK-NEXT:  # %bb.1: # %common.ret
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_2: # %exceptional_return
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:  .Ltmp2: # EH_LABEL
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %c = inttoptr i64 1 to ptr addrspace(1)
  %sp = invoke token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(void (ptr addrspace(1))) null, i32 1, i32 0, ptr addrspace(1) null, i32 0, i32 0) [ "gc-live"(ptr addrspace(1) null, ptr addrspace(1) %c) ]
          to label %common.ret unwind label %exceptional_return

common.ret:
  ret ptr addrspace(1) null

exceptional_return:
  %landing_pad = landingpad token
          cleanup
  %c.relocated = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token %landing_pad, i32 0, i32 1)
  ret ptr addrspace(1) %c.relocated
}

declare token @llvm.experimental.gc.statepoint.p0(i64 immarg, i32 immarg, ptr, i32 immarg, i32 immarg, ...)
declare ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token, i32 immarg, i32 immarg) #0

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
